image: hhucn/docker-discuss

before_script:
  - lein deps > /dev/null 2>&1
  - lein --version

test:
  stage: test
  script:
    - lein phantomtest

#linting:
#  stage: test
#  script:
#    - lein do check, ancient, kibit
#  allow_failure: true

build:
  script:
    - lein cljsbuild once min
