image: clojure

before_script:
  - lein clean
  #- lein kibit

build:
  script:
    - lein cljsbuild once min
  #artifacts:
  #  paths:
  #    - resources/public/js/compiled/discuss.js
  #  expire_in: 1 week
