image: clojure

before_script:
  - echo "Nothing to prepare..."

build:
  script:
    - lein --version
    - lein cljsbuild once min
  #artifacts:
  #  paths:
  #    - resources/public/js/compiled/discuss.js
  #  expire_in: 1 week
