image: hhucn/docker-discuss

test:
  stage: test
  script:
    - lein phantomtest

linting:
  stage: test
  script:
    - lein do check, ancient, kibit
  allow_failure: true

build_image:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE -f Dockerfile.prod .
    - docker push $CI_REGISTRY_IMAGE
#  only:
#    - master
