image: clojure

before_script:
  - lein deps > /dev/null 2>&1
  - lein --version

linting:
  stage: test
  script:
    - lein check
    - lein ancient
    - lein kibit

build:
  script:
    - lein cljsbuild once min