image: clojure:alpine

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2
  untracked: true

variables:
  LC_ALL: "C"

compile-js:
  stage: test
  script:
    - lein clean
    - lein cljsbuild once min

idiomatic?:
  stage: test
  script:
    - lein kibit
  allow_failure: true

build-image:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy-dev:
  image: clojure:openjdk-8-lein-alpine
  stage: deploy
  tags:
    - 40c
  before_script:
    - apk add --no-cache ca-certificates
    - rm -f mc
    - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc config host add argyou https://s3.cs.uni-duesseldorf.de $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - lein do clean, cljsbuild once min
    - ./mc cp resources/public/js/compiled/discuss.js argyou/discuss.js
  only:
    - develop

deploy-stable:
  image: clojure:openjdk-8-lein-alpine
  stage: deploy
  tags:
    - 40c
  before_script:
    - apk add --no-cache ca-certificates
    - rm -f mc
    - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc config host add argyou https://s3.cs.uni-duesseldorf.de $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - lein do clean, cljsbuild once min
    - ./mc cp resources/public/js/compiled/discuss.js argyou/discuss_stable.js
  only:
    - master
