image: clojure:alpine

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2
  untracked: true

variables:
  LC_ALL: "C"

compile-js:
  stage: test
  script:
    - lein clean
    - lein cljsbuild once min

idiomatic?:
  stage: test
  script:
    - lein kibit
  allow_failure: true


# ------------------------------------------------------------------------------

deploy-dev:
  image: clojure:openjdk-8-lein-alpine
  stage: deploy
  tags:
    - 40c
  before_script:
    - apk add --no-cache ca-certificates
    - rm -f mc
    - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc config host add cn https://s3.cs.uni-duesseldorf.de $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - lein do clean, cljsbuild once min
    - ./mc cp resources/public/js/compiled/discuss.js cn/argyou/discuss.js
  only:
    - develop

deploy-stable:
  image: clojure:openjdk-8-lein-alpine
  stage: deploy
  tags:
    - 40c
  before_script:
    - apk add --no-cache ca-certificates
    - rm -f mc
    - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc config host add cn https://s3.cs.uni-duesseldorf.de $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - lein do clean, cljsbuild once min
    - ./mc cp resources/public/js/compiled/discuss.js cn/argyou/discuss_stable.js
  only:
    - master

pages:
  stage: deploy
  before_script:
    - mkdir -p public
  script:
    - lein codox
    - mv target/docs/* public
  artifacts:
    paths:
      - public
  only:
    - develop
