image: clojure

before_script:
  - lein deps > /dev/null 2>&1
  - lein --version

linting:
  stage: test
  script:
    - lein do check, ancient, kibit
  allow_failure: true

build:
  script:
    - lein cljsbuild once min