image: hhucn/docker-discuss

cache:
  paths:
    - ~/.m2

test:
  stage: test
  script:
    - lein phantomtest

linting:
  stage: test
  script:
    - lein do ancient, kibit
  allow_failure: true

build_image:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - docker --version
    - echo $CI_REGISTRY_IMAGE
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile.prod -e "REMOTE_HOST:dbas/" -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
