image: hhucn/docker-discuss

before_script:
  - lein deps > /dev/null 2>&1
  - lein --version

test:
  stage: test
  script:
    - lein phantomtest

linting:
  stage: test
  script:
    - lein do check, ancient, kibit
  allow_failure: true

build_image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE -f Dockerfile.prod .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
