image: clojure

before_script:
  - echo "Nothing to prepare..."

linting:
  stage: test
  script:
    - lein ancient
    - lein kibit
  allow_failure: true

build:
  script:
    - lein --version
    - lein cljsbuild once min
  #artifacts:
  #  paths:
  #    - resources/public/js/compiled/discuss.js
  #  expire_in: 1 week
