version: 2
jobs:
  build:
    docker:
      - image: cmeter/clojure-phantomjs
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

  test:
    docker:
      - image: cmeter/clojure-phantomjs
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein cljsbuild once min

  analysis:
    docker:
      - image: cmeter/clojure-phantomjs
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein kibit || true

workflows:
  version: 2
  test_analysis:
    jobs:
      - build
      - test:
          requires:
            - build
      - analysis:
          requires:
            - build
